[[main]]
  name = "Home"
  pageRef = "index"
  weight = 1

[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ssouthcity"
  weight = 100
